// Polls NSPasteboard on a background thread and persists each new item as a
// file under CLIPBOARD_DIR. Files are named "<unix_ms>_<sha12>.<ext>" so the
// directory sorts chronologically by name (good enough until year 2286).
//
// Concealed/transient/auto-generated types are respected (password managers
// flag sensitive copies with these so history apps skip them).

use std::path::Path;
use std::sync::atomic::{AtomicBool, AtomicI64, Ordering};
use std::time::Duration;

use sha2::{Digest, Sha256};

pub const CLIPBOARD_DIR: &str = "/tmp/ishot_clipboard";

/// Read the current retention limit from the user's settings cache. Falls
/// back to 10 (the default) when the cache is empty. Always at least 1 so
/// `prune_to_max` never deletes the most recent entry on a misconfigured
/// install.
pub fn max_items() -> usize {
    crate::services::settings::load_cached().retention.max(1)
}

static IS_PAUSED: AtomicBool = AtomicBool::new(false);
static LAST_CHANGE_COUNT: AtomicI64 = AtomicI64::new(i64::MIN);

pub fn is_paused() -> bool {
    IS_PAUSED.load(Ordering::Relaxed)
}

pub fn toggle_paused() -> bool {
    let now = !IS_PAUSED.load(Ordering::Relaxed);
    IS_PAUSED.store(now, Ordering::Relaxed);
    now
}

pub fn start_polling(_app_handle: tauri::AppHandle) {
    if let Err(e) = std::fs::create_dir_all(CLIPBOARD_DIR) {
        eprintln!("[clipboard] failed to create dir: {}", e);
    }
    std::thread::spawn(|| {
        // Track the hash of the last persisted payload so repeated copies of
        // the same content don't accumulate duplicate files.
        let mut last_hash: Option<[u8; 32]> = None;
        loop {
            std::thread::sleep(Duration::from_millis(500));
            if is_paused() {
                continue;
            }
            poll_once(&mut last_hash);
        }
    });
}

#[cfg(target_os = "macos")]
#[allow(deprecated)]
fn poll_once(last_hash: &mut Option<[u8; 32]>) {
    use cocoa::base::{id, nil};
    use cocoa::foundation::NSString;
    use objc::{msg_send, sel, sel_impl, class};

    unsafe {
        let pasteboard: id = msg_send![class!(NSPasteboard), generalPasteboard];
        if pasteboard == nil {
            return;
        }
        let change_count: i64 = msg_send![pasteboard, changeCount];
        if change_count == LAST_CHANGE_COUNT.load(Ordering::Relaxed) {
            return;
        }
        LAST_CHANGE_COUNT.store(change_count, Ordering::Relaxed);

        // Check for password-manager / transient flags.
        let types: id = msg_send![pasteboard, types];
        if types != nil {
            let count: usize = msg_send![types, count];
            for i in 0..count {
                let t: id = msg_send![types, objectAtIndex: i];
                if t == nil { continue; }
                let cstr: *const std::os::raw::c_char = msg_send![t, UTF8String];
                if cstr.is_null() { continue; }
                let s = match std::ffi::CStr::from_ptr(cstr).to_str() {
                    Ok(v) => v,
                    Err(_) => continue,
                };
                if s == "org.nspasteboard.ConcealedType"
                    || s == "org.nspasteboard.TransientType"
                    || s == "org.nspasteboard.AutoGeneratedType"
                {
                    return;
                }
            }
        }

        // Prefer image: PNG first, then TIFF.
        let png_type = NSString::alloc(nil).init_str("public.png");
        let tiff_type = NSString::alloc(nil).init_str("public.tiff");
        let text_type = NSString::alloc(nil).init_str("public.utf8-plain-text");

        let png_data: id = msg_send![pasteboard, dataForType: png_type];
        let tiff_data: id = msg_send![pasteboard, dataForType: tiff_type];

        let bytes_opt: Option<Vec<u8>> = if png_data != nil {
            Some(ns_data_to_vec(png_data))
        } else if tiff_data != nil {
            Some(ns_data_to_vec(tiff_data))
        } else {
            None
        };

        if let Some(raw) = bytes_opt {
            let hash = sha256(&raw);
            if Some(hash) == *last_hash {
                return;
            }
            // Decode + re-encode as PNG so previews and re-copy paths only
            // ever touch one format.
            let img = match image::load_from_memory(&raw) {
                Ok(i) => i.to_rgba8(),
                Err(e) => { eprintln!("[clipboard] decode image: {}", e); return; }
            };
            let mut png_bytes: Vec<u8> = Vec::new();
            let encoder = image::codecs::png::PngEncoder::new(&mut png_bytes);
            if let Err(e) = image::ImageEncoder::write_image(
                encoder,
                img.as_raw(),
                img.width(),
                img.height(),
                image::ExtendedColorType::Rgba8,
            ) {
                eprintln!("[clipboard] encode png: {}", e);
                return;
            }
            if let Err(e) = write_item(&png_bytes, &hash, "png") {
                eprintln!("[clipboard] write image: {}", e);
                return;
            }
            *last_hash = Some(hash);
            prune_to_max();
            return;
        }

        let text_data: id = msg_send![pasteboard, stringForType: text_type];
        if text_data != nil {
            let cstr: *const std::os::raw::c_char = msg_send![text_data, UTF8String];
            if cstr.is_null() { return; }
            let s = match std::ffi::CStr::from_ptr(cstr).to_str() {
                Ok(v) => v,
                Err(_) => return,
            };
            if s.is_empty() { return; }
            let raw = s.as_bytes();
            let hash = sha256(raw);
            if Some(hash) == *last_hash {
                return;
            }
            if let Err(e) = write_item(raw, &hash, "txt") {
                eprintln!("[clipboard] write text: {}", e);
                return;
            }
            *last_hash = Some(hash);
            prune_to_max();
        }
    }
}

#[cfg(not(target_os = "macos"))]
fn poll_once(_last_hash: &mut Option<[u8; 32]>) {}

#[cfg(target_os = "macos")]
#[allow(deprecated)]
unsafe fn ns_data_to_vec(data: cocoa::base::id) -> Vec<u8> {
    use cocoa::foundation::NSData;
    let len = data.length() as usize;
    let ptr = data.bytes() as *const u8;
    if ptr.is_null() || len == 0 {
        return Vec::new();
    }
    std::slice::from_raw_parts(ptr, len).to_vec()
}

fn sha256(bytes: &[u8]) -> [u8; 32] {
    let mut h = Sha256::new();
    h.update(bytes);
    let out = h.finalize();
    let mut arr = [0u8; 32];
    arr.copy_from_slice(&out);
    arr
}

fn write_item(bytes: &[u8], hash: &[u8; 32], ext: &str) -> std::io::Result<()> {
    std::fs::create_dir_all(CLIPBOARD_DIR)?;
    let ms = chrono::Utc::now().timestamp_millis();
    let hex: String = hash.iter().take(6).map(|b| format!("{:02x}", b)).collect();
    let path = format!("{}/{}_{}.{}", CLIPBOARD_DIR, ms, hex, ext);
    std::fs::write(&path, bytes)?;
    Ok(())
}

pub fn prune_to_max() {
    let dir = Path::new(CLIPBOARD_DIR);
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    let mut files: Vec<String> = entries
        .filter_map(|e| e.ok())
        .filter_map(|e| e.file_name().into_string().ok())
        .collect();
    let limit = max_items();
    if files.len() <= limit {
        return;
    }
    // Lexicographic sort works because timestamps are zero-padded width.
    files.sort();
    let drop_count = files.len() - limit;
    for name in files.into_iter().take(drop_count) {
        let p = dir.join(name);
        if let Err(e) = std::fs::remove_file(&p) {
            eprintln!("[clipboard] prune {}: {}", p.display(), e);
        }
    }
}
